JonathonReinhart/scuba

README.md, example/.scuba.yml, example/run_example.sh, src/scuba
This adds support for aliases and closes #2.
=> Add support for aliases

src/scuba
Note that this also switches to using print_function, which helps with
future python3 compat.
See #19.
=> Add --verbose option

scuba/config.py
shlex.split() doesn't handle unicode input properly in Python 2.6.
First convert it to an ASCII string with just str().
This fixes #28.
=> Convert content to ASCII before shlex.split()

CHANGELOG.md, scuba/__main__.py, tests/test_main.py
=> Add -r option to run container as root

scuba/__main__.py, scuba/utils.py, tests/test_utils.py
=> Fix missing final line in format_cmdline()

CHANGELOG.md, scuba/__main__.py, tests/test_main.py
=> Allow arbitrary args to be passed to docker

scubainit/scubainit.c
Refactored out use_scuba_user() which includes the assertions.
This fixes #51
=> scubainit: Don't add scubauser if env vars not set

.travis.yml, ci/install_musl-libc.sh, scubainit/Makefile
=> Build scubainit with musl-libc

CHANGELOG.md, README.md, example/run_all.sh, example/scubainit_hooks/.scuba.yml, example/scubainit_hooks/run_example.sh, scuba/__main__.py, scuba/config.py, scubainit/scubainit.c, tests/test_config.py, tests/test_main.py
=> Implement scubainit hooks

scuba/__main__.py, scuba/utils.py, tests/test_utils.py, tests/utils.py
See #65
Note: User command will no longer be running as PID 1
=> Execute user command via shell

example/alias_multiline/.scuba.yml, example/alias_multiline/run_example.sh, example/common.yml, example/run_all.sh, scuba/__main__.py, scuba/config.py, tests/test_config.py, tests/test_main.py
=> Add support for enhanced aliases

CHANGELOG.md, example/per_alias_image/.scuba.yml, example/per_alias_image/run_example.sh, example/run_all.sh, scuba/__main__.py, scuba/config.py, tests/test_config.py
=> Implement alias-specific image specification

CHANGELOG.md, scuba/__main__.py, scuba/constants.py
=> Mount scuba top directory at same path in container

CHANGELOG.md, bash_completion/scuba, scuba/__main__.py, scuba/cmdlineargs.py, scuba/compat.py, scuba/config.py, setup.py, tests/test_cmdlineargs.py, tests/test_compat.py, tests/test_config.py, tests/test_main.py, tests/utils.py
=> Implement bash completion script

Makefile, scubainit/Makefile, setup.py
=> Automatically build scubainit

scuba/__main__.py, scuba/dockerutil.py, tests/test_dockerutil.py, tests/test_main.py
=> Handle images with entrypoint

scuba/__main__.py, tests/test_main.py
=> Add --image to override Docker image from .scuba.yml file

ci/install_musl-libc.sh
=> Fix musl libc installation

scuba/__main__.py, tests/test_main.py
=> scuba: Raise friendly error if no command given and no image Cmd

CHANGELOG.md, scuba/__main__.py, tests/test_main.py
=> Fix redirection of stdin

CHANGELOG.md, doc/yaml-reference.md, example/per_alias_image/.scuba.yml, scuba/config.py, tests/test_config.py, tests/test_main.py, tests/utils.py
=> Allow 'script' to be a single string in the Common Script Schema

setup.py
https://pythonhosted.org/an_example_pypi_project/setuptools.html#readme
=> Use README.md for long description

CHANGELOG.md, scuba/__main__.py, scuba/utils.py, tests/test_main.py, tests/test_utils.py
=> Add command-line support for passing environment variables

CHANGELOG.md, doc/yaml-reference.md, example/external_yaml_concatenate/.other.yml, example/external_yaml_concatenate/.scuba.yml, example/external_yaml_concatenate/run_example.sh, example/run_all.sh, scuba/config.py, scuba/utils.py, tests/test_main.py, tests/test_utils.py
This enables concatenation of scripts from multiple external yaml blocks, as suggested in #127.
=> Add support for nested scripts

scuba/config.py
=> Avoid unsafe loading of yaml documents

tests/test_config.py
=> Add tests for yaml loading changes

.travis.yml, CHANGELOG.md
PyYAML no longer supports Python 3.4
=> Remove Python 3.4 from test matrix

CHANGELOG.md, scuba/compat.py, scuba/config.py, tests/test_config.py, tests/utils.py
This enhancement was authored in part by Heath Moore.
This speeds up the loading of `.scuba.yml` files which have many references to another YAML file via `!from_yaml`.
Closes #146
=> Cache documents loaded by !from_yaml

CHANGELOG.md, scuba/__main__.py
=> Fix deprecation error with collections.Mapping

CHANGELOG.md, doc/yaml-reference.md, scuba/__main__.py, scuba/config.py, tests/test_config.py
=> Allow missing top level image

doc/yaml-reference.md, scuba/__main__.py, scuba/config.py, scuba/constants.py, tests/test_main.py
=> Add ability to specify shell and "run as root" in .scuba.yml

scubainit/scubainit.c
This restores the polarity to the way it was before b83f5ff0, but with a different name (since there is no "scuba user" now).
At this point, this is mostly superfluous, but this comment https://github.com/JonathonReinhart/scuba/pull/161#issuecomment-609207639 made me realize the distinction between "run as root" or "change user (*which could be root!*)" is important.
=> scubainit: Rename use_root to should_change_user

.github/workflows/build-test.yml, run_unit_tests.sh
Publish unit test results for the test matrix.
https://github.com/marketplace/actions/publish-unit-test-results#use-with-matrix-strategy
=> Publish unit test results

scuba/scuba.py, tests/utils.py
Miscellaneous cleanups encountered while refactoring
=> Minor cleanups

docs/configuration.rst
=> docs: Fix bind-mounts link

scubainit/src/entfiles.rs, scubainit/src/groups.rs, scubainit/src/main.rs, scubainit/src/passwd.rs, scubainit/src/shadow.rs
This is a follow-up from https://github.com/JonathonReinhart/scuba/pull/232#discussion_r1437728384.
cc @jammiess
=> Avoid lifetimes on EntFile{Reader,Writer}

.github/workflows/build-test.yml, CHANGELOG.md, pyproject.toml, scuba/scuba.py, scuba/version.py
=> Drop support for Python 3.7

CONTRIBUTING.md, dev_bootstrap.sh
Switch from 'virtualenv' to 'venv' which is part of the std library.
Add docker setup to both files.
=> Update dev bootstrap process

CHANGELOG.md, scuba/dockerutil.py, tests/test_dockerutil.py
=> Fix get_image_entrypoint() exception on Docker CE 28.2

.github/workflows/build-test.yml, CHANGELOG.md, pyproject.toml
=> Drop support for Python 3.8

scubainit/src/main.rs, scubainit/src/util.rs, tests/test_main.py
=> Parse SCUBAINIT_UMASK as an octal-encoded string
