src/scuba

Only pass `--user` if we're running locally (`DOCKER_HOST` is not set).
This fixes issue #4.

Fix permissions issue with remote docker

---

README.md
example/external_yaml_nested/.other.yml
example/external_yaml_nested/.scuba.yml
example/external_yaml_simple/.other.yml
example/external_yaml_simple/.scuba.yml
src/scuba

This adds a `!from_yaml` constructor to the YAML loader. With this one can specify the `image` in `.scuba.yml` by referring to a key in another YAML file.
This closes #7.

Add !from_yaml

---

CHANGELOG.md
src/scuba

This changes the in-container working directory from `/build` to `/scubaroot`.
This is more general (scuba doesn't *have* to be related to "building"), and clear (indicates that scuba was the one who set it up).

Change working directory name

---

src/scuba

`.scubainit` is used to perform initial actions in the container, prior to executing the user command.
It's primary purpose at this point is to create `scubauser` inside the container, to fix #11.

Add .scubainit

---

CHANGELOG.md
src/scuba

This better separates the remote vs. local execution logic.
When running a remote docker container (DOCKER_HOST is set), we don't do
any of the .scubainit stuff added in #13.
This fixes #17.

Don't use .scubainit when DOCKER_HOST is set

---

CHANGELOG.md
src/scuba

This adds a `--dry-run` option which complements `--verbose` for debugging / informational purposes.
Specifying `--dry-run` doesn't actually run Docker, and also skips the removal of temporary files, so they can be inspected.
This closes #19.

Add --dry-run

---

CHANGELOG.md
src/scuba

Instead of injecting `.scubainit` and starting the container with `/bin/sh /.scubainit`, this will:
- Inject `/etc/passwd`, `/etc/group`, and `/etc/shadow` files with `scubauser` added
- Go back to starting the user-command directly
This fixes #21 and #22.
The unfortunate part of this fix is that it removes the setting of `umask`, introduced in v1.3.0 by #16, because we no longer have a `.scubainit`.

Inject /etc/passwd and friends instead of .scubainit

---

.travis.yml
requirements.txt
run_tests.sh
scuba/__init__.py
tests/test_config.py

This enables Travis CI builds and Codecov.io coverage reporting.
Note that the tests are still failing on two Python versions:
- Python 2.6, due to some Unicode issue in the custom YAML loader
- Python 3.6.0a0 (nightly), due to some error with `inspect`:
`AttributeError: module 'inspect' has no attribute 'getargspec'`
https://docs.travis-ci.com/user/languages/python

Enable Travis CI builds

---

.travis.yml
scuba/__main__.py
scuba/config.py
scuba/filecleanup.py
tests/test_config.py
tests/test_filecleanup.py
tests/test_main.py
tests/utils.py

These tests exercise scuba using its command line arguments, but within the context of the unit tests, so nosetests is still easily able to get coverage.

Add tests for scuba.__main__

---

.travis.yml
run_full_tests.py
run_nosetests.sh
run_tests.sh

This runs `pip install .` to verify that setup.py works and can successfully install scuba. The test script then runs scuba (via process execution, instead of calling it's main), and verifies that basic operations are successful.

Add system test

---

CHANGELOG.md
scuba/__main__.py
scuba/utils.py

Currently when `--dry-run` is passed, it pretty-prints the docker run args with `pprint`. This change makes scuba print out an actual copy-and-pasteable command line, formatted to look nice as well.

Better dry run output

---

CHANGELOG.md
scuba/__main__.py
tests/test_main.py
tests/utils.py

This change will only pass `-t` to `docker run` when stdout is a TTY.
This fixes #31.

Don't pass -t to 'docker run' when stdout is redirected

---

setup.py

Whichever boilerplate setup.py was taken from used distutils. Update it to use setuptools so installation works when running setup.py directly, as opposed to via `pip install`.

Update setup.py to use setuptools

---

scubainit/scubainit.c

This fixes the mistake introduced in 888bf86cde0aaa3ae7cbeed142e6e257ff97a1ca.

scubainit: Set umask regardless of user

---

CHANGELOG.md
scubainit/scubainit.c
tests/test_main.py

This creates a home directory for the scubauser, and ensures the `HOME`, `USER`, and `LOGNAME` env vars are set properly.
This fixes #45.

Implement writable home directory

---

README.md
doc/yaml-reference.md

This pulls the `.scuba.yml` reference out into its own document, and leaves only a terse example in the main `README.md`.

Improve YAML documentation

---

CHANGELOG.md
run_nosetests.py
scuba/dockerutil.py
tests/test_dockerutil.py

This fixes #79, and adds some other small UI improvements around 'docker inspect'.

Improvements to get_image_command

---

scuba/__main__.py
scuba/config.py
tests/test_main.py

If --image is given, then .scuba.yml is allowed to be absent. In this
case, the project top directory will simply be defined as the current
directory (as Scuba cannot know where the "top" of your project is).
Closes #90

scuba: Allow .scuba.yml to be absent if --image is given

---

CHANGELOG.md
example/alias_multiline/.scuba.yml
scuba/__main__.py
scuba/config.py
scuba/utils.py
tests/test_config.py
tests/test_main.py

This prevents scuba from mangling constructs like && in scripts.
Doing so required re-doing all of the script parsing logic, treating scripts as lists of full command-line strings, instead of lists of parsed command-line lists.
Fixes #100

Fix script mangling

---

CHANGELOG.md
doc/yaml-reference.md
example/env_vars/.scuba.yml
example/env_vars/run_example.sh
scuba/__main__.py
scuba/config.py
scuba/utils.py
tests/test_config.py
tests/test_main.py
tests/test_utils.py
tests/utils.py

Add support for setting environment variable in .scuba.yml

---

.travis.yml
scuba/__main__.py
scuba/compat.py
scuba/config.py
scuba/dockerutil.py
scuba/utils.py
scuba/version.py
setup.py
tests/test_compat.py
tests/test_config.py
tests/test_main.py
tests/utils.py

Drop support for Python 2.6 and 3.2

---

ci/test_setup.sh
test-docker-images/build_all.sh
test-docker-images/entrypoint-test/Dockerfile
test-docker-images/entrypoint-test/build.sh
test-docker-images/entrypoint-test/entrypoint.sh
test-docker-images/hello/Dockerfile
test-docker-images/hello/build.sh
test-docker-images/hello/hello.sh
test-docker-images/scratch/Dockerfile
test-docker-images/scratch/build.sh
tests/setup_tests.sh
tests/test_dockerutil.py
tests/test_main.py

Rather than relying on external docker images for testing, build these simple images right from the scuba repository.

Build local docker images

---

scuba/__main__.py
tests/test_main.py

This is a breaking change.
Fixes #114

Don't run the entrypoint for each line in a multi-line script

---

CHANGELOG.md
scuba/__main__.py
scuba/config.py
scubainit/scubainit.c
tests/test_config.py
tests/test_main.py

This enables Scuba to override the image's configured `ENTRYPOINT`, via either the `--entrypoint` command-line argument, or via an `entrypoint` key in `.scuba.yml`.
Fixes #113

Enable scuba to override entrypoint

---

doc/yaml-reference.md
scuba/config.py
tests/test_config.py

Fixes #135
Specifically, this allows keys to contain escaped '.' characters.
It also updates `doc/yaml-reference.md` with a relevant example and adds
a unit test for the new functionality.

config: Update `!from_yml` to handle complex keys

---

CHANGELOG.md
scuba/__main__.py
scuba/constants.py
scubainit/scubainit.c
tests/test_main.py

#70 stopped using `/scubaroot` and instead uses the same path in the container as outside.
This does the same with the current username (and groupname): Instead of using `scubauser`, Scuba will use the username and groupname of the user invoking scuba.
This builds on top of and supersedes #138.

Use calling username/groupname instead of 'scubauser'

---

scubainit/scubainit.c

When trying to run a `node` container like so...
```yaml
image: none
aliases:
yarn:
image: node:12-alpine
script: yarn install
```
... I ran into the error message `scubainit: GID 1000 already exists in /etc/group`.
I guess the problem is that I am running locally as UID 1000, but the `node` packages also come with a `node` user with that UID by default (see https://github.com/nodejs/docker-node/issues/289).
I think we could safely proceed in this case; Linux should be able to deal with multiple `/etc/passwd` (and `/etc/group`, FWIW) entries pointing to the same numerical ID.
Not sure if this solves #109, though.

Ignore already existing UID/GIDs

---

tests/test_config.py
tests/test_dockerutil.py

This could have been done when we dropped Python 2.6 support.

Use assertRaises() context manager instead of assert_raises

---

.github/workflows/build-test.yml

This change should cause this workflow to be also run when someone creates or updates (pushes) a pull request.
https://github.community/t5/GitHub-Actions/Run-workflow-after-pushing-changes-to-a-PR/td-p/37016

Update build-test workflow to run on PR

---

scubainit/scubainit.c
tests/test_main.py

Commit 254fc4a7 (#139) relaxed the checks for existing passwd entries matching the UID being added (and group, GID).
This relaxes those checks even further by allowing existing entries which match both name *and* ID. We can't ignore the checks altogether because if we added a duplicate name with a different ID, the name would become ambiguous.
The only real use case I can think of here is for "root" but I suppose there could be others, and this seems correct.
Closes #94 
Supersedes #161

scubainit: Ignore matching passwd/group/shadow entries

---

.github/workflows/build-test.yml

Ideally we would run only on `push`, but that doesn't cover when someone creates/updates a PR on a fork, so we added the `pull_request` trigger in cf00c12f. That works well for forks.
However, that means when *I* push to a branch on my project with an associated PR, the tests all run twice.
Pushing to a branch without a PR, and expecting a build to run, seems unlikely enough that we can use `pull_request` exclusively for now.
Also, I discovered (in failed attempt #166) that the previous solution: `syncrhonize` doesn't cover when a PR is *first* opened. So we add the `opened` trigger.
(repeat of #166 for testing)

Run build/test workflow only on pull_request

---

CHANGELOG.md
scubainit/scubainit.c
tests/test_main.py

Consider this `.scuba.yml`:
```yaml
image: alpine:3.10
hooks:
root:
script:
- exit 42
```
Currently, when you run `scuba` it will output this:
```
scubainit: /.scuba/hooks/root.sh exited with status 10752
```
The reason is that `scubainit` is not properly decoding the return value of `system()`.
This MR updates `scubainit` to call `WEXITSTATUS()` to get the proper return code.
After:
```
scubainit: /.scuba/hooks/root.sh exited with status 42
```

scubainit: Properly handle system() return code

---

scuba/__main__.py

The autocomplete() stub needs to accept kwargs.
Fixes #170

Fix error where argcomplete is not installed

---

doc/yaml-reference.md
scuba/__main__.py
scuba/config.py
tests/test_config.py
tests/test_main.py

Docker arguments can now be specified in the scubafile at the top-level or per-alias. The order of precendence for a single run is:
1. Arguments provided on command line via `-d`
2. Per-alias `docker_args` key
2. Top-level `docker_args` key
Explicitly providing a null or empty string value for `docker_args` at the alias level overrides the top-level `docker_args`, and results in no extra args passed to docker.
Resolves #144

Allow docker arguments in scubafile

---

scuba/__main__.py
tests/test_main.py

This changes the behavior originally implemented in #177. Rather than overriding `docker_args` from `.scuba.yml`, now `-d` CLI args will be merged with them.
Closes #179.
cc @adamjseitz @xanarin

Append CLI --docker-arg to .scuba.yml docker_args

---

CHANGELOG.md
docs/configuration.rst
scuba/config.py
scuba/scuba.py
tests/test_config.py
tests/test_main.py
tests/test_scuba.py

This PR adds support for a new `volumes` key in `.scuba.yml` to bind-mount host directories into the container.
[**Latest docs build for `volumes` configuration**](https://scuba--186.org.readthedocs.build/en/186/configuration.html#volumes)
It supports both a simple form:
```yaml
volumes:
/var/lib/foo: /host/foo
```
...and a complex form:
```yaml
volumes:
/var/lib/foo:
hostpath: /host/foo
options: ro,cached
```
`volumes` can also be extended or overridden in an `alias`, as has now become the norm:
```yaml
volumes:
/var/lib/foo: /host/foo
aliases:
example:
volumes:
/var/lib/foo: /example/foo
/var/lib/bar: /example/bar
script:
- ls -l /var/lib/foo /var/lib/bar
```
This closes #140.

Add volumes to scubafile

---

CHANGELOG.md
docs/configuration.rst
docs/environment.rst

Even more updates to the Sphinx docs:
- Add tables in `.scuba.yml` configuration page
- Move alias-level override keys from `aliases` section to their own subsections
- Add missing documentation for `entrypoint:` node
- Fix various typos

More doc updates

---

docs/configuration.rst
scuba/config.py
scuba/utils.py
tests/test_config.py
tests/test_main.py
tests/test_utils.py

For more context on this change, see #191.

Expand env variables in volume paths in configuration file

---

scuba/__main__.py
scuba/scuba.py
tests/test_main.py

Docker creates host paths as root, which creates permission problems when volumes are within user-owned directories (like `$HOME`). If a host path doesn't exist, scuba duplicates Docker's behavior and attempts to create an empty directory at that location, but owned by the user that ran scuba.
Closes #195

Create host paths for volumes before starting Docker

---

.github/workflows/build-test.yml
CHANGELOG.md
setup.py

This drops support for Python 3.5 - 3.6.
This adds support (tests) for Python 3.10 - 3.11.
Fixes #202

Move Python support to 3.7 - 3.11

---

requirements.txt
run_full_tests.py
scuba/__main__.py
scuba/config.py
scuba/dockerutil.py
scuba/scuba.py
scuba/version.py
setup.py
tests/const.py
tests/test_main.py

1. Where appropriate, convert to [f-strings](https://peps.python.org/pep-0498/). This was accomplished using `flynt` (https://github.com/ikamensh/flynt) with manual review and a few changes.
2. Take advantage of the new `subprocess.run()` arguments: `text` and `capture_output`.

Use Python 3.7 language features

---

.github/workflows/publish-main.yml
README.md
VERSIONING.md

`master` has already been renamed `main` via the GitHub UI. Complete the remaining changes.

Rename 'master' branch to 'main'

---

.github/workflows/black.yml
CONTRIBUTING.md
code_format.py
docs/conf.py
docs/contributing.md
docs/index.rst
requirements.txt
run_full_tests.py
scuba/__main__.py
scuba/config.py
scuba/constants.py
scuba/dockerutil.py
scuba/scuba.py
scuba/utils.py
scuba/version.py
setup.py
tests/__init__.py
tests/conftest.py
tests/const.py
tests/test_config.py
tests/test_dockerutil.py
tests/test_main.py
tests/test_scuba.py
tests/test_utils.py
tests/utils.py

- The codebase is formatted with [Black](https://black.readthedocs.io/).
- A `code_format.py` script makes checking/fixing code formatting locally easy.
- A GitHub action enforces proper formatting for all PRs.

Format with Black

---

.github/workflows/build-test.yml
.github/workflows/publish-main.yml
.github/workflows/publish-release.yml
CHANGELOG.md
pyproject.toml
requirements.txt
setup.py

This is a step toward modernizing the project packaging, and allows us to begin defining tooling config in `pyproject.toml`.
References:
- https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
Tested:
- `python3 -m build`
- diff generated `scuba-*.dist-info/*` files and ensure only minimal, expected changes
Closes #203

Add pyproject.toml and move metadata from setup.py

---

.github/workflows/black.yml
code_format.py

Now that we use pyproject.toml, black can know this without being told.

Remove black --target-version

---

.github/workflows/build-test.yml
CHANGELOG.md
pyproject.toml
requirements.txt
scuba/__main__.py
scuba/argcomplete_stub.py
scuba/config.py
scuba/dockerutil.py
scuba/scuba.py
scuba/utils.py
scuba/version.py
static_analysis.sh
tests/test_scuba.py

This adds [PEP 484](https://peps.python.org/pep-0484/) type annotations to all files in the `scuba/` package, and enables type checking in CI via [mypy](https://mypy.readthedocs.io/).
Fixes #204.

Add type annotations

---

CHANGELOG.md
scuba/dockerutil.py
tests/test_dockerutil.py

This fixes a bug in `scuba.dockerutil.make_vol_opt()` whereby passing `options=[]` (which is what will typically happen if a volume is specified in `.scuba.yml` without including `options:`) will cause a docker CLI volume spec to erroneously include a trailing colon, which is fatal as of Docker CLI 24.0.5.
Fixes #215

Fix make_vol_opt trailing colon

---

docs/configuration.rst

Environment variables can be used in either the key (the container path) *or* in the host path, as shown in the accompanying example.
See also this test:
https://github.com/JonathonReinhart/scuba/blob/c6f3e62570/tests/test_config.py#L986
Also, move the existing note to a `note::` admonition, and indicate that unset variables will cause a config error.

docs: Correct docs regarding the use of env vars in volumes

---

test-docker-images/entrypoint-test/Dockerfile
test-docker-images/hello/Dockerfile

This resolves the issue where the files exist as e.g. 750 when building the image (due to paranoid umask 0027).
Fixes #220

Ensure files added to test-docker-images are executable by all

---

scuba/__main__.py
scuba/config.py
scuba/dockerutil.py
scuba/scuba.py
tests/test_config.py
tests/test_dockerutil.py
tests/test_scuba.py
tests/utils.py

[`pathlib.Path`](https://docs.python.org/3/library/pathlib.html), added in Python 3.4, is a welcome improvement to many places in Scuba, making it clear when objects are paths, and making many path manipulation actions much simpler.

Use path objects throughout

---

CHANGELOG.md
docs/configuration.rst
scuba/config.py
scuba/dockerutil.py
tests/test_config.py
tests/test_dockerutil.py
tests/test_main.py
tests/test_scuba.py
tests/utils.py

This enables the use of relative paths in a volume hostpath.
Previously, if one put this in `.scuba.yml`:
```yml
volumes:
/foo: foo
/foo:
hostpath: foo
```
`foo` would be interpreted by Docker as a *named volume*, resulting in an empty directory at `/foo`, which is certainly not what the user intended.
Or, if one tried to work around that problem and do this:
```yml
volumes:
/foo: ./foo
```
Then Docker would complain about the use of a relative path (a specifier containing a `/` but not starting with `/`), and suggest the use of an absolute path.
Now, when scuba encounters a relative path in a volume `hostpath`, it is interpreted as **relative to the scuba root** (the directory in which `.scbua.yml` is found). To avoid ambiguity with the old behavior, *relative paths must start with `./` …

Enable use of relative volume host-paths

---

.readthedocs.yaml

This is now required, apparently.
See:
- https://github.com/readthedocs/readthedocs.org/issues/8861#issuecomment-1025568797
- https://github.com/readthedocs/readthedocs.org/issues/8912
This fixes the error seen here:
https://readthedocs.org/projects/scuba/builds/22812400/
> Problem in your project's configuration. Invalid configuration option "build.os": build not found

Set build.os in .readthedocs.yml

---

setup.py

This fixes the problem where `pip install -e .` would not build scubainit. By fixing this, dev_bootstrap.sh does everything necessary to run scuba.

Build scubainit for setup.py develop command

---

scuba/scuba.py

The output format is not particularly important; it is a diagnostic facility. Switch from complex custom formatting to pprint.pformat().

scuba: Simplify ScubaDive.__str__

---

docs/configuration.rst
scuba/config.py
scuba/dockerutil.py
scuba/scuba.py
tests/test_config.py
tests/test_main.py
tests/utils.py

Named volumes were unintentionally supported prior to #227. This change restores the prior behavior while remaining unambiguiously compatible with relative bind-mounts added in #227.
This also adds support for explicit named volumes in complex form configuration.
Fixes #248

Add explicit support for mounting named volumes

---

CHANGELOG.md
scubainit/src/main.rs
tests/test_main.py

Rust pre-main code may change the SIGPIPE disposition to ignore:
* https://github.com/rust-lang/rust/issues/62569
* https://github.com/rust-lang/rust/issues/97889
We could use the nightly compiler flag `-Zon-broken-pipe=inherit` to disable this behavior. Instead, we take the simpler route and restore the default disposition ourselves.
Fixes #254

scubainit: Restore the default SIGPIPE action

---

tests/test_utils.py

Prior to this change, mypy was complaining:
```
tests/test_utils.py:169: error: BaseExcT_co_default? has no attribute "args"  [attr-defined]
```
Apparently, even though `pytest.raises()` is supposed to be generic on the given type parameter, mypy was still unaware that the `ExceptionInfo.value` property had that same type.
Adding a type hint takes care of the issue.
Fixes #266

tests: Fix mypy issue with pytest.raises()

---

scuba/config.py
scuba/dockerutil.py
scuba/scuba.py
tests/test_main.py
tests/test_utils.py
tests/utils.py

This eliminates all uses of these members of `typing`:  
`Tuple`, `List`, `Dict`, `Set`, `FrozenSet`, `Type`

Use type hinting generics from standard collections

---

code_format.py

This keeps it from losing its mind if you have a virtualenv with unformatted python code sitting in the project directory.

Run black on specific paths
